### PR TITLE
improve AVSwitch usage

### PR DESCRIPTION
**Pull request by jbleyel**
* remove getFramebufferScale
* do not use eAVSwitch

### CODE REVIEW

**Comment by kiddac** [comment]
unless this change is common in all oe-alliance images I wont be making the change

**Comment by jbleyel** [comment]
iAVSwitch is available on all oe-alliance images
getFramebufferScale is only needed for SD skins.

**Comment by jbleyel** [comment]
https://github.com/OpenViX/enigma2/blob/Developer/lib/python/Components/AVSwitch.py#L326
https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Components/AVSwitch.py#L149C2-L149C11

**Comment by kiddac** [comment]
ok, I will into some time over the next few days. My plugins do have skins for 1280, 1920 and 2650 (for dreambox) though.

And my plugins also have to be backwards compatible. Not everyone uses latest images. 

I would probably write in both with a try except.

**Comment by kiddac** [comment]
i have added in my own version of this now. Thanks

**Comment by jbleyel** [comment]
> i have added in my own version of this now. Thanks

Your version is wrong.

**Pull request closed without merging**
